### ISSUE TITLE
Installer without IOBit (Flatfiles)

### ISSUE THREAD

**Issue by Kobi-Blade** [BetterRTX/BetterRTX-Installer#22]
**Is your feature request related to a problem? Please describe.**
I not compromising the security of my computer to allow powershell scripts, not to mention IoBit is PUP.

**Describe the solution you'd like**
Give us the mod files directly, not all of us need a train on wheels to install mods, the entire script and even IoBit are entirely optional if you know what you doing.

**Describe alternatives you've considered**
This is a simple request, I can still get the files either way with custom powershell commands or even accessing them directly on google drive.

**Comment by ABUCKY0** [comment]
1. Not wanting to run a powershell script on your computer is a good thing. It means that you don’t randomly trust scripts. However, it is open source, so you can look through everything and see what exactly we do. 

2. IOBit does have a lot of people saying it is a PuP, but as for “IOBit Unlocker”, it doesn’t appear to have bad things being said for itself. 

3. I don’t want to have people download multiple applications just to install BetterRTX, but the reason we have to is because of the WindowsApps folder. It’s like really hard to open, and as far as I know, near impossible to edit directly. That’s where IOBit Unlocker comes it. We discovered it can edit files in the WindowsApps folder. I don’t like it, but it is currently the only option for easy setup.

4a. I lied in the above paragraph. If you use a Version Switcher, you can avoid the script and IOBit Unlocker, but I’m not going to pretend to know how to set that up. You can ask in the Minecraft RTX Discord on how to set that up. 

4b. You can visit the API directly or join the Minecraft RTX discord for the files we change.

**Comment by ABUCKY0** [comment]
I've taken ownership, I've given myself permissions, and I've applied the same permissions recursively to every folder. It still never allows me to edit it. By all means, feel free to tell us how it's done. Complaining about something we don't know how to do, claiming you did it, then not elaborating on how you did it doesn't help anybody.

**Comment by ABUCKY0** [comment]
@Kobi-Blade If I knew how to do it, me and @jasonjgardner would have dropped IOBit Unlocker already. I would like to drop IOBit Unlocker. If you want us to implement it, you will have to tell us because I just did more research on google and still failed to find a solution that works.

**Comment by ABUCKY0** [comment]
Only problem with using Psexec is that you need to have downloaded Pstools, which is still another download.

**Comment by ABUCKY0** [comment]
I've tried making a version that can do this, but it just like totally 100% breaks my Minecraft install, so I'm not going to test further. If you would like, you can send your installer here and I can test it again, but I don't want to have to reinstall Minecraft 30 times just to test this out.

**Comment by ABUCKY0** [comment]
It does close applications, but I don't see why it would change permissions. But either way, it works. 

I'm not well versed into /save and /restore with icals. 

Would I just save the permissions for the entire windowsapps folder or just the folder where the materials are held?

Like 
```ps1
icals /save "<data/renderer/materials directory path here>" acls.txt
takeown "<data/renderer/materials directory path here>"
#copy files into directory and delete old ones
icals /restore acls.txt
```
```

**Comment by ABUCKY0** [comment]
yeah I still can't figure out how to delete and place files in windowsapps. I've got the prerelease installer test without IOBIT with the following link, but still can't figure out how to do it. 
https://github.com/ABUCKY0/BetterRTX-Installer/blob/prerelease/BetterRTX_Installer%20(Test%20without%20IOBit).ps1

**Comment by ABUCKY0** [comment]
Yeah I probably won't be implementing this in the near future, so i'm going to close this issue.
